'use client';

import { useState, useRef, useEffect } from 'react';
import { sendMessage, getWelcome, getPublicStores, ChatResponse, Source, ChatLink } from '@/lib/api';

// ── TYPES ──
type ScreenState = 'setup' | 'consent' | 'chat';
type LanguageCode = 'it' | 'en' | 'fr' | 'pt' | 'ro' | 'es' | 'sq' | 'ar' | 'uk' | 'de';

interface Message {
    id: string;
    content: string;
    sender: 'user' | 'bot';
    sources?: Source[];
    links?: ChatLink[];
    stores_used?: string[];
    timestamp: Date;
}

interface DomainOption {
    val: string;
    ico: string;
    display?: string;
    desc?: string;
}

// ── TRANSLATIONS ──
const T: Record<LanguageCode, any> = {
    it: {
        hdrName: 'Assistente ULSS 9', hdrSub: 'Disponibile',
        setupTitle: 'Benvenuto,<br><em>come possiamo aiutarti?</em>',
        setupSub: 'Scegli la tua lingua e il servizio di interesse per ricevere risposte precise e pertinenti.',
        lblLang: 'Lingua / Language', lblDomain: 'Servizio / Reparto',
        langPh: 'Seleziona la tua lingua…', domainPh: 'Seleziona il servizio…',
        domainLoading: 'Caricamento servizi…',
        aiNotice: 'Le risposte sono <strong>generate dall\'intelligenza artificiale</strong> sulla base dei documenti ufficiali ULSS 9 Scaligera. Non sostituiscono il parere medico. Per emergenze chiama il <strong>118</strong>.',
        goLabel: 'Continua →',
        consentTitle: 'Informativa Privacy',
        consentBody: 'Questo servizio utilizza <strong>intelligenza artificiale</strong> per rispondere alle domande basandosi sui documenti ufficiali di <strong>ULSS 9 Scaligera</strong>.<br><br>Le domande sono elaborate tramite <strong>Google Gemini API</strong>. Il contenuto delle conversazioni <strong>non viene conservato</strong> al termine della sessione.<br><br>Gli indirizzi IP vengono registrati in forma <strong>anonimizzata</strong> nei log di sicurezza per un massimo di <strong>30 giorni</strong>.<br><br>Sta interagendo con un <strong>sistema automatico</strong>, non con un operatore umano. Per esigenze urgenti contatti il suo medico o chiami il <strong>118</strong>.',
        consentChk: 'Ho letto e accetto l\'informativa. Comprendo di interagire con un sistema di intelligenza artificiale e non con un operatore umano.',
        consentBtn: 'Inizia la Chat',
        newChat: 'Nuova chat', inpFoot: 'Assistente AI · ULSS 9 Scaligera · Non fornisce consulenza medica', inpPh: 'Scrivi la tua domanda…',
        welcome: 'Ciao! Sono il tuo assistente ULSS 9 Scaligera. Come posso aiutarti oggi?',
        chips: ['Orari punto prelievi', 'Come prenotare una visita', 'Dove si trova il pronto soccorso', 'Esenzione ticket sanitario'],
        errConn: 'Errore di connessione. Riprova tra poco.',
        domains: { general: 'Ricerca Generale', general_info: 'Informazioni generali', hours: 'Orari', locations: 'Sedi', services: 'Servizi' },
        domainDescs: { general: 'Cerca in tutti i servizi disponibili', general_info: 'Chi siamo, come accedere, numeri utili', hours: 'Ambulatori, prelievi, farmacie, visite', locations: 'Indirizzi, ospedali, distretti', services: 'Esami, visite, screening, assistenza' },
    },
    en: {
        hdrName: 'ULSS 9 Assistant', hdrSub: 'Available',
        setupTitle: 'Welcome,<br><em>how can we help you?</em>',
        setupSub: 'Choose your language and the service you need to receive accurate and relevant answers.',
        lblLang: 'Language', lblDomain: 'Service / Department',
        langPh: 'Select your language…', domainPh: 'Select a service…',
        domainLoading: 'Loading services…',
        aiNotice: 'Responses are <strong>generated by artificial intelligence</strong> based on official ULSS 9 documents. They do not replace medical advice. For emergencies call <strong>118</strong>.',
        goLabel: 'Continue →',
        consentTitle: 'Privacy Notice',
        consentBody: 'This service uses <strong>artificial intelligence</strong> to answer questions based on official documents from <strong>ULSS 9 Scaligera</strong>.<br><br>Questions are processed via <strong>Google Gemini API</strong>. Conversation content is <strong>not stored</strong> after the session ends.<br><br>IP addresses are recorded in <strong>anonymised form</strong> in security logs for a maximum of <strong>30 days</strong>.<br><br>You are interacting with an <strong>automated system</strong>, not a human operator. For urgent needs contact your doctor or call <strong>118</strong>.',
        consentChk: 'I have read and accept the privacy notice. I understand I am interacting with an artificial intelligence system, not a human operator.',
        consentBtn: 'Start Chat',
        newChat: 'New chat', inpFoot: 'AI Assistant · ULSS 9 Scaligera · Does not provide medical advice', inpPh: 'Type your question…',
        welcome: 'Hello! I\'m your ULSS 9 Scaligera assistant. How can I help you today?',
        chips: ['Blood draw opening hours', 'How to book an appointment', 'Where is the emergency room', 'Health ticket exemption'],
        errConn: 'Connection error. Please try again.',
        domains: { general: 'General Search', general_info: 'General info', hours: 'Opening hours', locations: 'Locations', services: 'Services' },
        domainDescs: { general: 'Search across all available services', general_info: 'Who we are, how to access', hours: 'Clinics, blood draw, pharmacies', locations: 'Addresses, hospitals, districts', services: 'Exams, visits, screening' },
    },
    fr: { hdrName: 'Assistant ULSS 9', hdrSub: 'Disponible', setupTitle: 'Bienvenue,<br><em>comment pouvons-nous vous aider?</em>', setupSub: 'Choisissez votre langue et le service qui vous intéresse pour des réponses précises.', lblLang: 'Langue', lblDomain: 'Service / Département', langPh: 'Sélectionnez votre langue…', domainPh: 'Sélectionnez un service…', domainLoading: 'Chargement…', aiNotice: 'Les réponses sont <strong>générées par intelligence artificielle</strong>.', goLabel: 'Continuer →', consentTitle: 'Confidentialité', consentBody: 'IA.', consentChk: 'J\'accepte.', consentBtn: 'Commencer', newChat: 'Nouveau', inpFoot: 'Assistant IA', inpPh: 'Votre question…', welcome: 'Bonjour!', chips: [], errConn: 'Erreur de connexion.', domains: {}, domainDescs: {} },
    de: { hdrName: 'ULSS 9 Assistent', hdrSub: 'Verfügbar', setupTitle: 'Willkommen,<br><em>wie können wir Ihnen helfen?</em>', setupSub: 'Wählen Sie Ihre Sprache.', lblLang: 'Sprache', lblDomain: 'Dienst', langPh: 'Sprache auswählen…', domainPh: 'Dienst auswählen…', domainLoading: 'Laden…', aiNotice: 'KI generiert.', goLabel: 'Weiter →', consentTitle: 'Datenschutz', consentBody: 'KI.', consentChk: 'Akzeptiert.', consentBtn: 'Start', newChat: 'Neu', inpFoot: 'KI Assistent', inpPh: 'Ihre Frage…', welcome: 'Hallo!', chips: [], errConn: 'Fehler.', domains: {}, domainDescs: {} },
    es: { hdrName: 'Asistente ULSS 9', hdrSub: 'Disponible', setupTitle: 'Bienvenido,<br><em>¿cómo podemos ayudarte?</em>', setupSub: 'Elige tu idioma.', lblLang: 'Idioma', lblDomain: 'Servicio', langPh: 'Selecciona idioma…', domainPh: 'Selecciona servicio…', domainLoading: 'Cargando…', aiNotice: 'Generado por IA.', goLabel: 'Continuar →', consentTitle: 'Privacidad', consentBody: 'IA.', consentChk: 'Acepto.', consentBtn: 'Iniciar chat', newChat: 'Nuevo chat', inpFoot: 'Asistente IA', inpPh: 'Tu pregunta…', welcome: '¡Hola!', chips: [], errConn: 'Error.', domains: {}, domainDescs: {} },
    pt: { hdrName: 'Assistente ULSS 9', hdrSub: 'Disponível', setupTitle: 'Bem-vindo,<br><em>como podemos ajudar?</em>', setupSub: 'Escolha seu idioma.', lblLang: 'Idioma', lblDomain: 'Serviço', langPh: 'Selecione idioma…', domainPh: 'Selecione serviço…', domainLoading: 'Carregando…', aiNotice: 'Gerado por IA.', goLabel: 'Continuar →', consentTitle: 'Privacidade', consentBody: 'IA.', consentChk: 'Aceito.', consentBtn: 'Iniciar', newChat: 'Novo', inpFoot: 'Assistente IA', inpPh: 'Pergunta…', welcome: 'Olá!', chips: [], errConn: 'Erro.', domains: {}, domainDescs: {} },
    ro: { hdrName: 'Asistent ULSS 9', hdrSub: 'Disponibil', setupTitle: 'Bun venit,<br><em>cum vă putem ajuta?</em>', setupSub: 'Alegeți limba.', lblLang: 'Limbă', lblDomain: 'Serviciu', langPh: 'Selectați limba…', domainPh: 'Selectați serviciul…', domainLoading: 'Se încarcă…', aiNotice: 'Generat de IA.', goLabel: 'Continuați →', consentTitle: 'Confidențialitate', consentBody: 'IA.', consentChk: 'Accept.', consentBtn: 'Începeți', newChat: 'Nou', inpFoot: 'Asistent IA', inpPh: 'Întrebare…', welcome: 'Bună!', chips: [], errConn: 'Eroare.', domains: {}, domainDescs: {} },
    sq: { hdrName: 'Asistenti ULSS 9', hdrSub: 'I disponueshëm', setupTitle: 'Mirë se vini,<br><em>si mund t\'ju ndihmojmë?</em>', setupSub: 'Zgjidhni gjuhën.', lblLang: 'Gjuha', lblDomain: 'Shërbimi', langPh: 'Zgjidhni gjuhën…', domainPh: 'Zgjidhni shërbimin…', domainLoading: 'Duke ngarkuar…', aiNotice: 'Gjeneruar nga IA.', goLabel: 'Vazhdo →', consentTitle: 'Privatësinë', consentBody: 'IA.', consentChk: 'Pranoj.', consentBtn: 'Filloni', newChat: 'I ri', inpFoot: 'Asistent IA', inpPh: 'Pyetje…', welcome: 'Përshëndetje!', chips: [], errConn: 'Gabim.', domains: {}, domainDescs: {} },
    ar: { hdrName: 'مساعد', hdrSub: 'متاح', setupTitle: 'مرحباً', setupSub: 'اختر لغتك.', lblLang: 'اللغة', lblDomain: 'الخدمة', langPh: 'اختر لغتك…', domainPh: 'اختر خدمة…', domainLoading: 'جارٍ التحميل…', aiNotice: 'الذكاء الاصطناعي.', goLabel: 'متابعة →', consentTitle: 'الخصوصية', consentBody: 'الذكاء الاصطناعي.', consentChk: 'أوافق.', consentBtn: 'ابدأ', newChat: 'جديد', inpFoot: 'مساعد', inpPh: 'سؤالك…', welcome: 'مرحباً!', chips: [], errConn: 'خطأ.', domains: {}, domainDescs: {} },
    uk: { hdrName: 'Асистент', hdrSub: 'Доступний', setupTitle: 'Ласкаво просимо', setupSub: 'Оберіть мову.', lblLang: 'Мова', lblDomain: 'Служба', langPh: 'Оберіть мову…', domainPh: 'Оберіть службу…', domainLoading: 'Завантаження…', aiNotice: 'ШІ.', goLabel: 'Продовжити →', consentTitle: 'Конфіденційність', consentBody: 'ШІ.', consentChk: 'Приймаю.', consentBtn: 'Почати', newChat: 'Новий', inpFoot: 'ШІ', inpPh: 'Питання…', welcome: 'Привіт!', chips: [], errConn: 'Помилка.', domains: {}, domainDescs: {} },
};

const LANG_OPTIONS = [
    { val: 'it', ico: '🇮🇹', name: 'Italiano' },
    { val: 'en', ico: '🇬🇧', name: 'English' },
    { val: 'ro', ico: '🇷🇴', name: 'Română' },
    { val: 'ar', ico: '🇸🇦', name: 'العربية' },
    { val: 'uk', ico: '🇺🇦', name: 'Українська' },
    { val: 'fr', ico: '🇫🇷', name: 'Français' },
    { val: 'de', ico: '🇩🇪', name: 'Deutsch' },
    { val: 'es', ico: '🇪🇸', name: 'Español' },
    { val: 'pt', ico: '🇧🇷', name: 'Português' },
    { val: 'sq', ico: '🇦🇱', name: 'Shqip' },
] as const;

// Known domains that have local translations — don't use backend display_name for these
const KNOWN_DOMAINS = new Set(['general_info', 'hours', 'locations', 'services']);

// Strip vendor prefix (e.g. "ulss9-") and underscore-humanise for unknown custom domains
const humanizeDisplayName = (name: string) =>
    name.replace(/^[a-z0-9]+-/i, '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

// The "search all stores" option — always prepended, not a fallback
const GENERAL_OPTION: DomainOption = { val: 'general', ico: '🔍' };


export default function NewChatWidget() {
    const [mounted, setMounted] = useState(false);
    const [isOpen, setIsOpen] = useState(false);
    const [screen, setScreen] = useState<ScreenState>('setup');

    const [lang, setLang] = useState<LanguageCode | null>(null);
    const [domainKey, setDomainKey] = useState<string | null>(null);
    const [consentGiven, setConsentGiven] = useState(false);
    const [chkConsent, setChkConsent] = useState(false);

    const [openSel, setOpenSel] = useState<'lang' | 'domain' | null>(null);

    const [messages, setMessages] = useState<Message[]>([]);
    const [inputValue, setInputValue] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [suggestions, setSuggestions] = useState<string[]>([]);

    // Domain options: fetched from API only — no hardcoded fallback
    const [domainOptions, setDomainOptions] = useState<DomainOption[]>([]);
    const [loadingDomains, setLoadingDomains] = useState(true);

    const messagesEndRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLTextAreaElement>(null);

    // Client-only mount to prevent hydration mismatch
    useEffect(() => { setMounted(true); }, []);

    // Fetch public stores for the category picker (is_public=true, unauthenticated)
    useEffect(() => {
        getPublicStores()
            .then(stores => {
                const icos: Record<string, string> = { general_info: '🏥', hours: '🕐', locations: '📍', services: '🩺' };
                const opts: DomainOption[] = [
                    GENERAL_OPTION,
                    ...stores.map(s => ({
                        val: s.domain,
                        ico: icos[s.domain] ?? '📂',
                        // For known domains, let the translation (tr.domains) handle the label.
                        // For custom admin-created domains, humanize the backend display_name.
                        display: KNOWN_DOMAINS.has(s.domain) ? undefined : humanizeDisplayName(s.display_name),
                        desc: s.description || undefined,
                    })),
                ];
                setDomainOptions(opts);
            })
            .catch(() => {
                // Backend unreachable: only show the general/search-all option
                setDomainOptions([GENERAL_OPTION]);
            })
            .finally(() => setLoadingDomains(false));
    }, []);

    // Read consent from sessionStorage on mount
    useEffect(() => {
        if (typeof window !== 'undefined') {
            const saved = sessionStorage.getItem('ulss9_consent');
            if (saved === '1') setConsentGiven(true);
            window.parent.postMessage({ type: 'CHATBOT_RESIZE', isOpen: false }, '*');
        }
    }, []);

    // Tell parent iframe to resize when open state changes
    useEffect(() => {
        if (typeof window !== 'undefined') {
            window.parent.postMessage({ type: 'CHATBOT_RESIZE', isOpen }, '*');
        }
    }, [isOpen]);

    // Scroll to bottom on new messages
    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [messages, isLoading]);

    const toggleOpen = () => setIsOpen(prev => !prev);
    const closeAllSel = () => setOpenSel(null);
    const pickLang = (l: LanguageCode) => { setLang(l); closeAllSel(); };
    const pickDomain = (d: string) => { setDomainKey(d); closeAllSel(); };

    const tr = lang ? (T[lang] || T.it) : T.it;

    const onContinueSetup = () => {
        if (consentGiven) { startChat(); } else { setScreen('consent'); }
    };

    const startChat = async () => {
        setConsentGiven(true);
        if (typeof window !== 'undefined') sessionStorage.setItem('ulss9_consent', '1');
        setScreen('chat');
        setMessages([]);
        setIsLoading(true);
        try {
            const data = await getWelcome(lang || 'it');
            setMessages([{ id: 'welcome', content: data.message, sender: 'bot', timestamp: new Date() }]);
            setSuggestions(data.suggestions || tr.chips);
        } catch {
            setMessages([{ id: 'welcome', content: tr.welcome, sender: 'bot', timestamp: new Date() }]);
            setSuggestions(tr.chips || []);
        } finally {
            setIsLoading(false);
            setTimeout(() => inputRef.current?.focus(), 100);
        }
    };

    const newChat = () => {
        setLang(null);
        setDomainKey(null);
        setMessages([]);
        setScreen('setup');
        setInputValue('');
    };

    const handleSend = async (text: string) => {
        if (!text.trim() || isLoading) return;

        setMessages(p => [...p, { id: `u-${Date.now()}`, content: text, sender: 'user', timestamp: new Date() }]);
        setInputValue('');
        setIsLoading(true);
        setSuggestions([]);

        try {
            const domainVal = domainKey === 'general' ? null : domainKey;
            const res = await sendMessage(text, domainVal, lang || 'it');
            setMessages(p => [...p, {
                id: `b-${Date.now()}`,
                content: res.response,
                sender: 'bot',
                sources: res.sources,
                links: res.links,
                stores_used: res.stores_used,
                timestamp: new Date(),
            }]);
            if (res.suggested_questions?.length) setSuggestions(res.suggested_questions);
        } catch (e) {
            const detail = e instanceof Error ? e.message : tr.errConn;
            setMessages(p => [...p, { id: `err-${Date.now()}`, content: detail, sender: 'bot', timestamp: new Date() }]);
        } finally {
            setIsLoading(false);
            inputRef.current?.focus();
        }
    };

    const onKey = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(inputValue); }
    };

    const lIcon = lang ? LANG_OPTIONS.find(o => o.val === lang)?.ico : null;
    const lName = lang ? LANG_OPTIONS.find(o => o.val === lang)?.name : tr.langPh;

    const dOpt = domainKey ? domainOptions.find(o => o.val === domainKey) : null;
    const dIcon = dOpt?.ico ?? null;
    const dName = domainKey ? (dOpt?.display ?? tr.domains[domainKey] ?? domainKey) : tr.domainPh;

    return (
        <div 
            className="fixed inset-0 pointer-events-none sm:p-6 p-0 z-50 overflow-hidden font-sans"
            data-gramm="false" 
            data-gramm_editor="false" 
            data-enable-grammarly="false" 
            data-quillbot-element="false"
            suppressHydrationWarning
        >

            {/* ── LAUNCHER ── */}
            <div className="absolute sm:bottom-6 sm:right-6 bottom-4 right-4 flex flex-col items-end gap-3 pointer-events-auto z-[9999]">
                <div className={`text-[11px] font-medium text-white bg-[var(--ulss9-blue)] px-3.5 py-1.5 rounded-full shadow-[var(--sh-md)] border border-white/20 whitespace-nowrap animate-slide-up transition-opacity duration-300 ${(!isOpen && mounted) ? 'opacity-100' : 'opacity-0 pointer-events-none hidden'}`}>
                    {mounted ? tr.hdrName : 'Assistente ULSS 9'}
                </div>

                <button
                    onClick={toggleOpen}
                    className="w-14 h-14 rounded-full border-none cursor-pointer flex items-center justify-center relative transition-transform duration-300 shadow-[0_6px_24px_rgba(0,159,216,0.5)] bg-gradient-to-br from-[var(--ulss9-cyan-m)] to-[var(--ulss9-cyan)] hover:scale-110 active:scale-95"
                    aria-label="Apri assistente"
                >
                    <span className={`absolute -inset-1.5 rounded-full border-[1.5px] border-[var(--ulss9-cyan)]/45 animate-lring pointer-events-none ${isOpen ? 'hidden' : 'block'}`} />
                    <span className={`absolute top-0 right-0 w-3.5 h-3.5 rounded-full bg-[var(--ulss9-orange)] border-2 border-white transition-opacity ${isOpen ? 'hidden' : 'block'}`} />
                    <span className={`absolute transition-all duration-300 ${isOpen ? 'opacity-0 rotate-45 scale-50' : 'opacity-100 rotate-0 scale-100'} flex items-center justify-center`}>
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <path d="M20 2H4C2.9 2 2 2.9 2 4v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z" fill="white" opacity="0.95" />
                            <circle cx="8" cy="12" r="1.15" fill="var(--ulss9-cyan)" />
                            <circle cx="12" cy="12" r="1.15" fill="var(--ulss9-cyan)" />
                            <circle cx="16" cy="12" r="1.15" fill="var(--ulss9-cyan)" />
                        </svg>
                    </span>
                    <span className={`absolute transition-all duration-300 ${!isOpen ? 'opacity-0 -rotate-45 scale-50' : 'opacity-100 rotate-0 scale-100'} flex items-center justify-center`}>
                        <svg width="16" height="16" viewBox="0 0 18 18" fill="none">
                            <path d="M14 4L4 14M4 4l10 10" stroke="white" strokeWidth="2.3" strokeLinecap="round" />
                        </svg>
                    </span>
                </button>
            </div>

            {/* ── WIDGET WINDOW ── */}
            <div
                className={`absolute sm:bottom-24 sm:right-6 bottom-0 right-0 flex flex-col rounded-t-[var(--r)] sm:rounded-b-[var(--r)] overflow-hidden bg-[var(--ulss9-off-white)] border border-[var(--ulss9-border)] shadow-[var(--sh-lg)] sm:w-[392px] w-full sm:h-[640px] h-[92dvh] sm:max-h-[calc(100vh-7.5rem)] pointer-events-auto origin-bottom-right transition-all duration-300 z-[9998] ${isOpen ? 'scale-100 translate-y-0 opacity-100' : 'scale-[0.86] translate-y-4 opacity-0 pointer-events-none'}`}
                role="dialog" aria-label="Assistente ULSS 9"
            >
                {/* HEADER */}
                <div className="shrink-0 px-[1.15rem] pt-[1rem] pb-[0.95rem] bg-gradient-to-br from-[var(--ulss9-blue-d)] to-[var(--ulss9-blue)] relative overflow-hidden">
                    <div className="absolute -top-[40px] -right-[50px] w-[160px] h-[160px] rounded-full bg-[radial-gradient(circle,rgba(0,159,216,0.25),transparent_65%)] pointer-events-none" />
                    <div className="absolute -bottom-[30px] left-[20px] w-[100px] h-[100px] rounded-full bg-[radial-gradient(circle,rgba(0,159,216,0.12),transparent_70%)] pointer-events-none" />
                    <div className="flex items-center gap-[0.8rem] relative">
                        <div className="w-[40px] h-[40px] rounded-full shrink-0 bg-white/20 border-2 border-white/25 flex items-center justify-center text-[1.15rem] shadow-[0_2px_8px_rgba(0,0,0,0.2)]">🏥</div>
                        <div className="flex-1">
                            <div className="font-serif text-[1.05rem] font-medium text-white tracking-[0.01em] leading-[1.2]" suppressHydrationWarning>
                                {mounted ? tr.hdrName : 'Assistente ULSS 9'}
                            </div>
                            <div className="flex items-center gap-[0.38rem] text-[0.67rem] text-white/60 font-light mt-[0.12rem] tracking-[0.02em]">
                                <span className="w-[5px] h-[5px] rounded-full bg-[#7ee8a2] shrink-0 animate-dotpulse" />
                                <span>{tr.hdrSub}</span>
                            </div>
                        </div>
                        {screen === 'chat' && (
                            <button onClick={newChat} className="flex items-center gap-[0.35rem] shrink-0 py-[0.38rem] px-[0.75rem] bg-white/10 border border-white/20 rounded-full text-white/75 text-[0.67rem] font-medium cursor-pointer transition-all hover:bg-white/20 hover:text-white hover:scale-105">
                                <svg width="10" height="10" viewBox="0 0 10 10" fill="none"><path d="M5 1v8M1 5h8" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" /></svg>
                                <span>{tr.newChat}</span>
                            </button>
                        )}
                    </div>
                </div>

                {/* SCREEN: SETUP */}
                {screen === 'setup' && (
                    <div className="flex-1 flex flex-col min-h-0 animate-mfade">
                        <div className="flex-[1] overflow-y-auto pt-[1.4rem] px-[1.15rem] pb-[0.8rem] flex flex-col gap-[1.15rem] custom-scrollbar" onClick={closeAllSel}>
                            <div>
                                <div className="font-serif text-[1.45rem] font-light text-[var(--ulss9-ink)] leading-[1.15] tracking-[0.01em]" dangerouslySetInnerHTML={{ __html: tr.setupTitle }} />
                                <div className="text-[0.76rem] text-[var(--ulss9-ink-70)] font-light leading-[1.65] mt-[0.3rem]">{tr.setupSub}</div>
                            </div>

                            {/* Language Select */}
                            <div className="flex flex-col gap-[0.45rem] relative">
                                <div className="text-[0.6rem] font-semibold tracking-[0.16em] uppercase text-[var(--ulss9-ink-45)]">{tr.lblLang}</div>
                                <div className="relative" onClick={e => e.stopPropagation()}>
                                    <button onClick={() => setOpenSel(openSel === 'lang' ? null : 'lang')} className={`w-full flex items-center gap-[0.55rem] bg-white border-[1.5px] rounded-[var(--r-s)] py-[0.76rem] pl-[0.95rem] pr-[2.5rem] text-[0.82rem] cursor-pointer text-left shadow-[var(--sh-sm)] transition-all ${openSel === 'lang' ? 'border-[var(--ulss9-cyan)] shadow-[0_0_0_3px_rgba(0,159,216,0.15)]' : 'border-[var(--ulss9-border-m)]'} hover:border-[var(--ulss9-cyan)] hover:bg-[var(--ulss9-off-white)]`}>
                                        <span className={lang ? 'text-[var(--ulss9-ink)] font-medium' : 'text-[var(--ulss9-ink-45)]'}>
                                            {lIcon && <span className="mr-2">{lIcon}</span>}
                                            <span>{lName}</span>
                                        </span>
                                        <span className={`absolute right-[0.9rem] top-1/2 -translate-y-1/2 text-[var(--ulss9-ink-45)] transition-transform ${openSel === 'lang' ? 'rotate-180' : ''}`}>
                                            <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 4L6 8.5L10 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>
                                        </span>
                                    </button>
                                    {/* Language dropdown — opens DOWNWARD */}
                                    <div className={`absolute top-[calc(100%+5px)] left-0 right-0 z-50 bg-white border-[1.5px] border-[var(--ulss9-border-m)] rounded-[var(--r-s)] shadow-[var(--sh-md)] overflow-y-auto custom-scrollbar transition-all duration-200 origin-top ${openSel === 'lang' ? 'max-h-[240px] opacity-100 pointer-events-auto' : 'max-h-0 opacity-0 pointer-events-none'}`}>
                                        {LANG_OPTIONS.map(o => (
                                            <div key={o.val} onClick={() => pickLang(o.val)} className={`flex items-center gap-[0.65rem] px-[0.95rem] py-[0.7rem] text-[0.81rem] cursor-pointer border-b border-[var(--ulss9-ink-04)] last:border-b-0 transition-colors ${lang === o.val ? 'bg-[var(--ulss9-cyan-l)] text-[var(--ulss9-blue)] font-medium' : 'text-[var(--ulss9-ink-70)] hover:bg-[var(--ulss9-cyan-xl)] hover:text-[var(--ulss9-ink)]'}`}>
                                                <span className="text-[1rem] shrink-0 w-[20px] text-center">{o.ico}</span>
                                                <div className="flex-1 truncate">{o.name}</div>
                                                {lang === o.val && <span className="ml-auto text-[0.7rem]">✓</span>}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* Domain Select */}
                            <div className="flex flex-col gap-[0.45rem] relative">
                                <div className="text-[0.6rem] font-semibold tracking-[0.16em] uppercase text-[var(--ulss9-ink-45)]">{tr.lblDomain}</div>
                                <div className="relative" onClick={e => e.stopPropagation()}>
                                    <button onClick={() => setOpenSel(openSel === 'domain' ? null : 'domain')} className={`w-full flex items-center gap-[0.55rem] bg-white border-[1.5px] rounded-[var(--r-s)] py-[0.76rem] pl-[0.95rem] pr-[2.5rem] text-[0.82rem] cursor-pointer text-left shadow-[var(--sh-sm)] transition-all ${openSel === 'domain' ? 'border-[var(--ulss9-cyan)] shadow-[0_0_0_3px_rgba(0,159,216,0.15)]' : 'border-[var(--ulss9-border-m)]'} hover:border-[var(--ulss9-cyan)] hover:bg-[var(--ulss9-off-white)]`}>
                                        <span className={domainKey ? 'text-[var(--ulss9-ink)] font-medium' : 'text-[var(--ulss9-ink-45)]'}>
                                            {dIcon && <span className="mr-2">{dIcon}</span>}
                                            <span>{dName}</span>
                                        </span>
                                        <span className={`absolute right-[0.9rem] top-1/2 -translate-y-1/2 text-[var(--ulss9-ink-45)] transition-transform ${openSel === 'domain' ? 'rotate-180' : ''}`}>
                                            <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 4L6 8.5L10 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>
                                        </span>
                                    </button>
                                    {/* Domain dropdown — opens DOWNWARD (consistent with language, avoids overflow clip) */}
                                    <div className={`absolute top-[calc(100%+5px)] left-0 right-0 z-50 bg-white border-[1.5px] border-[var(--ulss9-border-m)] rounded-[var(--r-s)] shadow-[var(--sh-md)] overflow-y-auto custom-scrollbar transition-all duration-200 origin-top ${openSel === 'domain' ? 'max-h-[240px] opacity-100 pointer-events-auto' : 'max-h-0 opacity-0 pointer-events-none'}`}>
                                        {loadingDomains ? (
                                            <div className="px-[0.95rem] py-[0.9rem] text-[0.78rem] text-[var(--ulss9-ink-45)] text-center">{tr.domainLoading}</div>
                                        ) : domainOptions.length === 0 ? (
                                            <div className="px-[0.95rem] py-[0.9rem] text-[0.78rem] text-[var(--ulss9-ink-45)] text-center">Nessun servizio disponibile</div>
                                        ) : domainOptions.map(o => (
                                            <div key={o.val} onClick={() => pickDomain(o.val)} className={`flex items-start gap-[0.65rem] px-[0.95rem] py-[0.7rem] text-[0.81rem] cursor-pointer border-b border-[var(--ulss9-ink-04)] last:border-b-0 transition-colors ${domainKey === o.val ? 'bg-[var(--ulss9-cyan-l)] text-[var(--ulss9-blue)]' : 'hover:bg-[var(--ulss9-cyan-xl)]'}`}>
                                                <span className="text-[1rem] shrink-0 w-[20px] text-center mt-0.5">{o.ico}</span>
                                                <div className="flex-1 min-w-0">
                                                    <div className={`truncate ${domainKey === o.val ? 'font-medium' : 'text-[var(--ulss9-ink)]'}`}>{o.display ?? tr.domains[o.val] ?? o.val}</div>
                                                    <div className="text-[0.65rem] text-[var(--ulss9-ink-45)] font-light mt-[0.05rem]">{o.desc ?? tr.domainDescs[o.val] ?? ''}</div>
                                                </div>
                                                {domainKey === o.val && <span className="ml-auto text-[0.7rem] text-[var(--ulss9-blue)] mt-1">✓</span>}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* AI Notice */}
                            <div className="flex gap-[0.7rem] items-start bg-[var(--ulss9-cyan-xl)] rounded-[var(--r-s)] px-[0.95rem] py-[0.85rem] border border-[var(--ulss9-cyan)]/20 border-l-[3px] border-l-[var(--ulss9-cyan)]">
                                <span className="text-[1rem] shrink-0 mt-[0.05rem]">🤖</span>
                                <div className="text-[0.71rem] text-[var(--ulss9-ink-70)] leading-[1.7] font-light" dangerouslySetInnerHTML={{ __html: tr.aiNotice }} />
                            </div>
                        </div>

                        <div className="px-[1.15rem] pb-[1.15rem] shrink-0">
                            <button
                                disabled={!lang || !domainKey}
                                onClick={onContinueSetup}
                                className="w-full p-[0.9rem] rounded-[var(--r-s)] border-none bg-gradient-to-br from-[var(--ulss9-blue-m)] to-[var(--ulss9-blue)] text-white font-semibold text-[0.88rem] tracking-[0.03em] cursor-pointer shadow-[0_4px_18px_rgba(0,91,154,0.4)] transition-all disabled:opacity-30 disabled:cursor-not-allowed disabled:shadow-none hover:enabled:opacity-90 hover:enabled:-translate-y-px hover:enabled:shadow-[0_6px_24px_rgba(0,91,154,0.5)]"
                            >
                                {tr.goLabel}
                            </button>
                        </div>
                    </div>
                )}

                {/* SCREEN: CONSENT */}
                {screen === 'consent' && (
                    <div className="flex-1 flex flex-col min-h-0 animate-mfade">
                        <div className="flex-[1] overflow-y-auto pt-[1.25rem] px-[1.15rem] pb-[0.75rem] flex flex-col gap-[0.95rem] custom-scrollbar">
                            <div className="bg-white border border-[var(--ulss9-border)] rounded-[var(--r-s)] py-[1.05rem] px-[1.1rem] shadow-[var(--sh-sm)]">
                                <div className="font-serif text-[1rem] font-medium text-[var(--ulss9-ink)] mb-[0.7rem] tracking-[0.01em]">{tr.consentTitle}</div>
                                <div className="text-[0.72rem] text-[var(--ulss9-ink-70)] leading-[1.8] font-light" dangerouslySetInnerHTML={{ __html: tr.consentBody }} />
                            </div>
                            <label className="flex items-start gap-[0.7rem] bg-[var(--ulss9-orange-l)] border-[1.5px] border-transparent rounded-[var(--r-s)] px-[0.95rem] py-[0.85rem] cursor-pointer transition-colors hover:border-[var(--ulss9-orange)]/45">
                                <input type="checkbox" checked={chkConsent} onChange={e => setChkConsent(e.target.checked)} className="w-[16px] h-[16px] shrink-0 accent-[var(--ulss9-orange)] mt-[2px] cursor-pointer" />
                                <div className="text-[0.73rem] text-[var(--ulss9-ink-70)] leading-[1.6] font-light">{tr.consentChk}</div>
                            </label>
                        </div>
                        <div className="px-[1.15rem] pb-[1.15rem] shrink-0">
                            <button
                                disabled={!chkConsent}
                                onClick={startChat}
                                className="w-full p-[0.9rem] rounded-[var(--r-s)] border-none bg-gradient-to-br from-[#f07a30] to-[var(--ulss9-orange)] text-white font-semibold text-[0.88rem] tracking-[0.03em] cursor-pointer shadow-[0_4px_18px_rgba(232,104,26,0.35)] transition-all disabled:opacity-30 disabled:cursor-not-allowed disabled:shadow-none hover:enabled:opacity-90 hover:enabled:-translate-y-px"
                            >
                                {tr.consentBtn}
                            </button>
                        </div>
                    </div>
                )}

                {/* SCREEN: CHAT */}
                {screen === 'chat' && (
                    <div className="flex-1 flex flex-col min-h-0 animate-mfade">
                        <div className="shrink-0 flex items-center gap-[0.45rem] flex-wrap py-[0.52rem] px-[1.05rem] bg-white border-b border-[var(--ulss9-border)]">
                            <span className="inline-flex items-center gap-[0.28rem] bg-[var(--ulss9-cyan-l)] border border-[var(--ulss9-cyan)]/20 rounded-full px-[0.65rem] py-[0.22rem] text-[0.64rem] font-semibold text-[var(--ulss9-blue)] tracking-[0.03em] uppercase">
                                {lIcon && <span>{lIcon}</span>} <span>{lang}</span>
                            </span>
                            <span className="inline-flex items-center gap-[0.28rem] bg-[var(--ulss9-cyan-l)] border border-[var(--ulss9-cyan)]/20 rounded-full px-[0.65rem] py-[0.22rem] text-[0.64rem] font-semibold text-[var(--ulss9-blue)] tracking-[0.03em] uppercase">
                                {dIcon && <span>{dIcon}</span>} <span>{dName}</span>
                            </span>
                        </div>

                        <div className="flex-[1] overflow-y-auto py-[1.05rem] px-[1.05rem] flex flex-col gap-[0.9rem] bg-[var(--ulss9-light)] custom-scrollbar">
                            {messages.map(m => (
                                <div key={m.id} className={`flex gap-[0.55rem] animate-mfade ${m.sender === 'user' ? 'flex-row-reverse' : ''}`}>
                                    <div className={`w-[28px] h-[28px] rounded-full shrink-0 flex items-center justify-center text-[0.64rem] font-bold tracking-tight mt-px ${m.sender === 'user' ? 'bg-[var(--ulss9-orange-l)] text-[var(--ulss9-orange)]' : 'bg-[var(--ulss9-cyan-l)] text-[var(--ulss9-blue)]'}`}>
                                        {m.sender === 'user' ? 'Tu' : 'AI'}
                                    </div>
                                    <div className={`max-w-[82%] flex flex-col gap-[0.32rem] ${m.sender === 'user' ? 'items-end' : ''}`}>
                                        <div
                                            className={`text-[0.8rem] leading-[1.7] py-[0.68rem] px-[0.9rem] ${m.sender === 'user' ? 'bg-gradient-to-br from-[var(--ulss9-blue-m)] to-[var(--ulss9-blue)] text-white rounded-[0.9rem_0.25rem_0.9rem_0.9rem] shadow-[0_2px_10px_rgba(0,91,154,0.35)]' : 'bg-white border border-[var(--ulss9-border)] text-[var(--ulss9-ink-70)] rounded-[0.25rem_0.9rem_0.9rem_0.9rem] shadow-[var(--sh-sm)]'}`}
                                            dangerouslySetInnerHTML={{ __html: m.content.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br/>') }}
                                        />
                                        {m.sender === 'bot' && m.sources?.[0]?.title && (
                                            <div className="text-[0.61rem] text-[var(--ulss9-cyan)] font-medium flex items-center gap-[0.25rem] pl-[0.1rem]">
                                                📄 {m.sources[0].title}
                                            </div>
                                        )}
                                    </div>
                                </div>
                            ))}

                            {isLoading && (
                                <div className="flex gap-[0.55rem] animate-mfade">
                                    <div className="w-[28px] h-[28px] rounded-full shrink-0 flex items-center justify-center text-[0.64rem] font-bold tracking-tight mt-px bg-[var(--ulss9-cyan-l)] text-[var(--ulss9-blue)]">AI</div>
                                    <div className="bg-white border border-[var(--ulss9-border)] rounded-[0.25rem_0.9rem_0.9rem_0.9rem] py-[0.68rem] px-[0.9rem] shadow-[var(--sh-sm)] flex gap-[5px] items-center">
                                        <span className="w-[5px] h-[5px] rounded-full bg-[var(--ulss9-cyan)] animate-td" />
                                        <span className="w-[5px] h-[5px] rounded-full bg-[var(--ulss9-cyan)] animate-td" style={{ animationDelay: '0.16s' }} />
                                        <span className="w-[5px] h-[5px] rounded-full bg-[var(--ulss9-cyan)] animate-td" style={{ animationDelay: '0.32s' }} />
                                    </div>
                                </div>
                            )}

                            {suggestions.length > 0 && !isLoading && (
                                <div className="flex flex-wrap gap-[0.38rem] mt-[0.12rem] animate-mfade ml-[35px]">
                                    {suggestions.map((sg, i) => (
                                        <button key={i} onClick={() => handleSend(sg)} className="py-[0.32rem] px-[0.68rem] bg-white border border-[var(--ulss9-border-m)] rounded-full text-[0.67rem] font-medium text-[var(--ulss9-blue)] cursor-pointer transition-all shadow-[var(--sh-sm)] hover:bg-[var(--ulss9-cyan-l)] hover:border-[var(--ulss9-cyan)]/35 hover:text-[var(--ulss9-blue-d)] hover:-translate-y-px">
                                            {sg}
                                        </button>
                                    ))}
                                </div>
                            )}
                            <div ref={messagesEndRef} />
                        </div>

                        <div className="shrink-0 pt-[0.75rem] px-[1.05rem] pb-[1rem] bg-white border-t border-[var(--ulss9-border)]">
                            <div className="flex gap-[0.5rem] items-end bg-[var(--ulss9-off-white)] border-[1.5px] rounded-[1.3rem] pl-[0.9rem] pr-[0.5rem] py-[0.5rem] transition-all focus-within:border-[var(--ulss9-cyan)] focus-within:shadow-[0_0_0_3px_rgba(0,159,216,0.12)] border-[var(--ulss9-border-m)]">
                                <div className="flex-[1] min-w-0 relative flex items-center">
                                    <textarea
                                        ref={inputRef}
                                        value={inputValue}
                                        onChange={e => setInputValue(e.target.value)}
                                        onKeyDown={onKey}
                                        disabled={isLoading}
                                        placeholder={tr.inpPh}
                                        rows={1}
                                        className="w-full bg-transparent border-none outline-none text-[0.81rem] text-[var(--ulss9-ink)] resize-none leading-[1.55] min-h-[22px] max-h-[90px] overflow-y-auto p-0 placeholder-[var(--ulss9-ink-45)] disabled:cursor-not-allowed custom-scrollbar"
                                        data-gramm="false"
                                        data-gramm_editor="false"
                                        data-enable-grammarly="false"
                                        data-quillbot-element="false"
                                        spellCheck={false}
                                    />
                                </div>
                                <button
                                    disabled={!inputValue.trim() || isLoading}
                                    onClick={() => handleSend(inputValue)}
                                    className="w-[36px] h-[36px] shrink-0 rounded-full border-none bg-gradient-to-br from-[var(--ulss9-cyan-m)] to-[var(--ulss9-cyan)] cursor-pointer flex items-center justify-center self-end shadow-[0_2px_8px_rgba(0,159,216,0.4)] transition-all hover:enabled:scale-105 hover:enabled:shadow-[0_4px_14px_rgba(0,159,216,0.55)] active:enabled:scale-95 disabled:opacity-40 disabled:cursor-not-allowed"
                                >
                                    {isLoading ? (
                                        <span style={{
                                            display: 'inline-block', width: '13px', height: '13px',
                                            border: '2px solid rgba(255,255,255,0.3)',
                                            borderTopColor: 'white', borderRadius: '50%',
                                            animation: 'widgetSpin 0.65s linear infinite',
                                        }} />
                                    ) : (
                                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                                            <path d="M22 2L11 13M22 2L15 22l-4-9-9-4 20-7z" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                    )}
                                </button>
                            </div>
                            <div className="mt-[0.52rem] text-center text-[0.57rem] text-[var(--ulss9-ink-45)] tracking-[0.04em]">
                                {tr.inpFoot}
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
